name: Build and test

on:
  push:
    branches: 
      - develop
      - staging
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the project
      run: dotnet build --no-restore
    - name: Run integration tests only
      if: github.ref == 'refs/heads/staging'
      run: dotnet test --no-build --verbosity normal
    - name: Run unit tests only
      if: github.ref == 'refs/heads/develop'
      run: dotnet test --no-build --verbosity normal
